/*
* generated by Xtext
*/
package it.xsemantics.example.fj.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FJAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("it/xsemantics/example/fj/parser/antlr/internal/InternalFJ.tokens");
	}
}
