/*
* generated by Xtext
*/
package it.xsemantics.example.fj.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import it.xsemantics.example.fj.services.FJGrammarAccess;

public class FJParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FJGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected it.xsemantics.example.fj.parser.antlr.internal.InternalFJParser createParser(XtextTokenStream stream) {
		return new it.xsemantics.example.fj.parser.antlr.internal.InternalFJParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public FJGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FJGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
