/*******************************************************************************
 * Copyright (c) 2013-2017 Lorenzo Bettini.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Lorenzo Bettini - Initial contribution and API
 *******************************************************************************/

/*
* generated by Xtext
*/
package it.xsemantics.example.fjcached.validation;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class FjcachedJavaValidator extends it.xsemantics.example.fjcached.validation.AbstractFjcachedJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(it.xsemantics.example.fj.fj.FjPackage.eINSTANCE);
	    result.add(it.xsemantics.example.fjcached.fjcached.FjcachedPackage.eINSTANCE);
		return result;
	}
}
