/*
* generated by Xtext
*/
package it.xsemantics.example.fjcached.validation;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class FjcachedJavaValidator extends it.xsemantics.example.fjcached.validation.AbstractFjcachedJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(it.xsemantics.example.fj.fj.FjPackage.eINSTANCE);
	    result.add(it.xsemantics.example.fjcached.fjcached.FjcachedPackage.eINSTANCE);
		return result;
	}
}
