/*
 * generated by Xtext 2.20.0
 */
package org.eclipse.xsemantics.example.fjcached.ui.outline;

import org.eclipse.xsemantics.example.fj.ui.outline.FJOutlineTreeProvider;
import org.eclipse.xsemantics.example.fjcached.fjcached.FjCachedProgram;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class FjcachedOutlineTreeProvider extends FJOutlineTreeProvider {

	protected void _createChildren(DocumentRootNode parentNode,
			FjCachedProgram program) {
		super._createChildren(parentNode, program.getCachedprogram());
	}
}
