/*
 * generated by Xtext
 */
package it.xsemantics.example.expressions;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpressionsRuntimeModule extends it.xsemantics.example.expressions.AbstractExpressionsRuntimeModule {

}
