/*
* generated by Xtext
*/
package it.xsemantics.example.lambda.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class LambdaOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
