/*
 * generated by Xtext
 */
package it.xsemantics.example.fjcached.ui.contentassist

import it.xsemantics.example.fjcached.ui.contentassist.AbstractFjcachedProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FjcachedProposalProvider extends AbstractFjcachedProposalProvider {
}
