/*
* generated by Xtext
*/
package it.xsemantics.example.lambda.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import it.xsemantics.example.lambda.services.LambdaGrammarAccess;

public class LambdaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LambdaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected it.xsemantics.example.lambda.parser.antlr.internal.InternalLambdaParser createParser(XtextTokenStream stream) {
		return new it.xsemantics.example.lambda.parser.antlr.internal.InternalLambdaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public LambdaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LambdaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
