/*
* generated by Xtext
*/
package it.xsemantics.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XsemanticsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("it/xsemantics/dsl/parser/antlr/internal/InternalXsemantics.tokens");
	}
}
