/*
* generated by Xtext
*/
package it.xsemantics.example.expressions;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ExpressionsUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return it.xsemantics.example.expressions.ui.internal.ExpressionsActivator.getInstance().getInjector("it.xsemantics.example.expressions.Expressions");
	}
	
}
