/*
 * generated by Xtext
 */
package it.xsemantics.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XsemanticsUiModule extends it.xsemantics.dsl.ui.AbstractXsemanticsUiModule {
	public XsemanticsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
