/*******************************************************************************
 * Copyright (c) 2013-2017 Lorenzo Bettini.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Lorenzo Bettini - Initial contribution and API
 *******************************************************************************/

/*
 * generated by Xtext
 */
package it.xsemantics.example.lambda;

import it.xsemantics.example.lambda.validation.LambdaValidatorFilter;
import it.xsemantics.example.lambda.xsemantics.LambdaStringRepresentationWithTypeBeautifier;
import it.xsemantics.runtime.StringRepresentation;
import it.xsemantics.runtime.validation.XsemanticsValidatorFilter;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class LambdaRuntimeModule extends
		it.xsemantics.example.lambda.AbstractLambdaRuntimeModule {

	public Class<? extends StringRepresentation> bindStringProvider() {
		return LambdaStringRepresentationWithTypeBeautifier.class;
	}

	public Class<? extends XsemanticsValidatorFilter> bindXsemanticsValidatorFilter() {
		return LambdaValidatorFilter.class;
	}
}
