/*
 * generated by Xtext 2.20.0
 */
package org.eclipse.xsemantics.example.fjcached.ui.labeling;

import org.eclipse.xsemantics.example.fj.ui.labeling.FJLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class FjcachedLabelProvider extends FJLabelProvider {

	// Labels and icons can be computed like this:
	
//	String text(Greeting ele) {
//		return "A greeting to " + ele.getName();
//	}
//
//	String image(Greeting ele) {
//		return "Greeting.gif";
//	}
}
