/*
 * generated by Xtext 2.20.0
 */
package org.eclipse.xsemantics.example.lambda;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LambdaStandaloneSetup extends LambdaStandaloneSetupGenerated {

	public static void doSetup() {
		new LambdaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
