/*
 * generated by Xtext
 */
package it.xsemantics.example.fj.ui.contentassist;

import it.xsemantics.example.fj.ui.contentassist.AbstractFJProposalProvider;

import org.eclipse.emf.ecore.EObject;

/**
 * A specialization to use the label provider to show the proposals in the
 * context assist.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
public class FJProposalProvider extends AbstractFJProposalProvider {

	/**
	 * Redefined so that it uses the label provider to show the text (display
	 * string) of the content assist.
	@Override
	protected ICompletionProposal createCompletionProposal(EObject element,
			String proposal, String displayString,
			ContentAssistContext contentAssistContext) {
		return createCompletionProposal(proposal, labelProvider
				.getText(element), getImage(element), contentAssistContext);
	}
	 */

	@Override
	public String getDisplayString(EObject element, String qualifiedName, String shortName) {
		return getLabelProvider().getText(element);
	}
}
