/*
* generated by Xtext
*/
package it.xsemantics.example.expressions.ui.contentassist;

import it.xsemantics.example.expressions.ui.contentassist.AbstractExpressionsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ExpressionsProposalProvider extends AbstractExpressionsProposalProvider {

}
