/*
* generated by Xtext
*/
package it.xsemantics.example.fj;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FJUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return it.xsemantics.example.fj.ui.internal.FJActivator.getInstance().getInjector("it.xsemantics.example.fj.FJ");
	}
	
}
