/*
 * generated by Xtext 2.20.0
 */
package org.eclipse.xsemantics.example.expressions.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xsemantics.example.expressions.ExpressionsRuntimeModule;
import org.eclipse.xsemantics.example.expressions.ExpressionsStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ExpressionsIdeSetup extends ExpressionsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ExpressionsRuntimeModule(), new ExpressionsIdeModule()));
	}
	
}
