/*******************************************************************************
 * Copyright (c) 2013-2017 Lorenzo Bettini.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Lorenzo Bettini - Initial contribution and API
 *******************************************************************************/

/*
 * generated by Xtext 2.20.0
 */
package org.eclipse.xsemantics.example.fj;

import org.eclipse.xsemantics.example.fj.typing.FjStringRepresentation;
import org.eclipse.xsemantics.runtime.StringRepresentation;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FJRuntimeModule extends AbstractFJRuntimeModule {
	public Class<? extends StringRepresentation> bindStringRepresentation() {
		return FjStringRepresentation.class;
	}
}
