/*******************************************************************************
 * Copyright (c) 2013-2017 Lorenzo Bettini.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Lorenzo Bettini - Initial contribution and API
 *******************************************************************************/

/*
 * generated by Xtext
 */
package org.eclipse.xsemantics.example.fj;

import org.eclipse.xsemantics.example.fj.typing.FjStringRepresentation;
import org.eclipse.xsemantics.runtime.StringRepresentation;


/**
 * Use this class to register components to be used within the IDE.
 */
public class FJRuntimeModule extends org.eclipse.xsemantics.example.fj.AbstractFJRuntimeModule {

	/*
	@Override
	public Class<? extends ILinkingService> bindILinkingService() {
		return FJLinkingService.class;
	}
	*/

//	@Override
//	public Class<? extends XtextResource> bindXtextResource() {
//		return FJLinkingResource.class;
//	}
//
//	/* (non-Javadoc)
//	 * @see org.eclipse.xtext.service.DefaultRuntimeModule#bindIResourceFactory()
//	 */
//	public Class<? extends XtextResourceFactory> bindXtextResourceFactory() {
//		  return FJResourceFactory.class;
//	}

	/*
	@Override
	public Class<? extends ITransientValueService> bindITransientValueService() {
		// TODO Auto-generated method stub
		return FJTransientValueService.class;
	}
	*/
	
	public Class<? extends StringRepresentation> bindStringRepresentation() {
		return FjStringRepresentation.class;
	}
}
