/*
 * generated by Xtext 2.20.0
 */
package org.eclipse.xsemantics.example.fj;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FJStandaloneSetup extends FJStandaloneSetupGenerated {

	public static void doSetup() {
		new FJStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
