<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lambda"
    nsURI="http://xsemantics.sf.net/example/lambda/Lambda" nsPrefix="lambda">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringConstant" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntConstant" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="int" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arithmetics" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abstraction" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeVariable" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typevarName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fun" eType="#//Term" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrowType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntType" eSuperTypes="#//BasicType"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//BasicType"/>
</ecore:EPackage>
