/*
 * generated by Xtext 2.20.0
 */
package org.eclipse.xsemantics.example.fjcached.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xsemantics.example.fjcached.FjcachedRuntimeModule;
import org.eclipse.xsemantics.example.fjcached.FjcachedStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FjcachedIdeSetup extends FjcachedStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FjcachedRuntimeModule(), new FjcachedIdeModule()));
	}
	
}
