/*
 * generated by Xtext 2.20.0
 */
package org.eclipse.xsemantics.example.fjcached.ide;


/**
 * Use this class to register ide components.
 */
public class FjcachedIdeModule extends AbstractFjcachedIdeModule {
}
