/*
 * generated by Xtext
 */
package it.xsemantics.example.fjcached.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FjcachedUiModule extends it.xsemantics.example.fjcached.ui.AbstractFjcachedUiModule {
	public FjcachedUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
