/*
* generated by Xtext
*/
package it.xsemantics.dsl.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class XsemanticsDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

}
