/*
 * generated by Xtext 2.20.0
 */
package org.eclipse.xsemantics.example.fj.tests

import com.google.inject.Inject
import org.eclipse.xsemantics.example.fj.fj.Program
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(FJInjectorProvider)
class FJParsingTest {
	@Inject
	ParseHelper<Program> parseHelper

	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			class A {
				int myInt;
				int getMyInt() { return this.myInt; }
			}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
